package com.nedap.archie.rminfo;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates {@link RMInvariants} from the invariants in {@link ArchieRMInfoLookup}.
 * <p>
 * Run the main method to regenerate the class after adding, removing or un-ignoring an invariant.
 * {@link RMInvariantsTest} fails if the committed class is out of date.
 */
public class RMInvariantsGenerator {

    static final String FILE_PATH = "src/main/java/com/nedap/archie/rminfo/RMInvariants.java";

    public static void main(String[] args) throws IOException {
        Path path = getFilePath();
        Files.writeString(path, generate(), StandardCharsets.UTF_8);
        System.out.println("Written " + path.toAbsolutePath());
    }

    static Path getFilePath() {
        // Works both when run from the root project directory and from the openehr-rm directory
        Path fromRoot = Path.of("openehr-rm", FILE_PATH);
        return Files.isDirectory(Path.of("openehr-rm")) ? fromRoot : Path.of(FILE_PATH);
    }

    private static final String FILE_TEMPLATE = """
            package com.nedap.archie.rminfo;

            /**
             * Names of all invariants that are not ignored, for use in
             * {@code ValidationConfiguration.Builder#enabledInvariants(Set)}.
             * <p>
             * Generated by RMInvariantsGenerator, do not edit by hand.
             */
            @SuppressWarnings("unused")
            public final class RMInvariants {

                private RMInvariants() {
                }
            %s}
            """;

    private static final String TYPE_TEMPLATE = """

                public static final class %1$s {

                    private %1$s() {
                    }

            %2$s    }
            """;

    private static final String CONSTANT_TEMPLATE = """
                    public static final String %s = "%s.%s";
            """;

    static String generate() {
        String types = ArchieRMInfoLookup.getInstance().getAllTypes().stream()
                .sorted(Comparator.comparing(RMTypeInfo::getRmName))
                .map(RMInvariantsGenerator::generateType)
                .collect(Collectors.joining());
        return FILE_TEMPLATE.formatted(types);
    }

    private static String generateType(RMTypeInfo type) {
        List<String> invariantNames = type.getInvariants().stream()
                // only invariants declared on this type, inherited ones are covered by the parent type
                .filter(invariant -> invariant.getMethod().getDeclaringClass().equals(type.getJavaClass()))
                .filter(invariant -> !invariant.getAnnotation().ignored())
                .map(invariant -> invariant.getAnnotation().value())
                .distinct()
                .sorted()
                .collect(Collectors.toList());
        if (invariantNames.isEmpty()) {
            return "";
        }
        String constants = invariantNames.stream()
                .map(invariantName -> CONSTANT_TEMPLATE.formatted(toConstantName(invariantName), type.getRmName(), invariantName))
                .collect(Collectors.joining());
        return TYPE_TEMPLATE.formatted(type.getRmName(), constants);
    }

    private static String toConstantName(String invariantName) {
        return invariantName
                .replaceAll("([a-z0-9])([A-Z])", "$1_$2")
                .replaceAll("[^A-Za-z0-9]+", "_")
                .toUpperCase();
    }
}
