package com.nedap.archie.rminfo;

/**
 * Names of all invariants that are not ignored, for use in
 * {@code ValidationConfiguration.Builder#enabledInvariants(Set)}.
 * <p>
 * Generated by RMInvariantsGenerator, do not edit by hand.
 */
@SuppressWarnings("unused")
public final class RMInvariants {

    private RMInvariants() {
    }

    public static final class ACTIVITY {

        private ACTIVITY() {
        }

        public static final String ACTION_ARCHETYPE_ID_VALID = "ACTIVITY.Action_archetype_id_valid";
    }

    public static final class ARCHETYPED {

        private ARCHETYPED() {
        }

        public static final String RM_VERSION_VALID = "ARCHETYPED.Rm_version_valid";
    }

    public static final class AUDIT_DETAILS {

        private AUDIT_DETAILS() {
        }

        public static final String CHANGE_TYPE_VALID = "AUDIT_DETAILS.Change_type_valid";
        public static final String SYSTEM_ID_VALID = "AUDIT_DETAILS.System_id_valid";
    }

    public static final class CODE_PHRASE {

        private CODE_PHRASE() {
        }

        public static final String CODE_STRING_VALID = "CODE_PHRASE.Code_string_valid";
    }

    public static final class COMPOSITION {

        private COMPOSITION() {
        }

        public static final String CATEGORY_VALIDITY = "COMPOSITION.Category_validity";
        public static final String IS_ARCHETYPE_ROOT = "COMPOSITION.Is_archetype_root";
        public static final String LANGUAGE_VALID = "COMPOSITION.Language_valid";
        public static final String TERRITORY_VALID = "COMPOSITION.Territory_valid";
    }

    public static final class DV_AMOUNT {

        private DV_AMOUNT() {
        }

        public static final String ACCURACY_IS_PERCENT_VALIDITY = "DV_AMOUNT.Accuracy_is_percent_validity";
        public static final String ACCURACY_VALID = "DV_AMOUNT.Accuracy_valid";
    }

    public static final class DV_EHR_URI {

        private DV_EHR_URI() {
        }

        public static final String SCHEME_VALID = "DV_EHR_URI.Scheme_valid";
    }

    public static final class DV_ENCAPSULATED {

        private DV_ENCAPSULATED() {
        }

        public static final String CHARSET_VALID = "DV_ENCAPSULATED.Charset_valid";
        public static final String LANGUAGE_VALID = "DV_ENCAPSULATED.Language_valid";
    }

    public static final class DV_IDENTIFIER {

        private DV_IDENTIFIER() {
        }

        public static final String ID_VALID = "DV_IDENTIFIER.Id_valid";
    }

    public static final class DV_MULTIMEDIA {

        private DV_MULTIMEDIA() {
        }

        public static final String COMPRESSION_ALGORITHM_VALID = "DV_MULTIMEDIA.Compression_algorithm_valid";
        public static final String INTEGRITY_CHECK_ALGORITHM_VALIDITY = "DV_MULTIMEDIA.Integrity_check_algorithm_validity";
        public static final String INTEGRITY_CHECK_VALIDITY = "DV_MULTIMEDIA.Integrity_check_validity";
        public static final String MEDIA_TYPE_VALID = "DV_MULTIMEDIA.Media_type_valid";
        public static final String NOT_EMPTY = "DV_MULTIMEDIA.Not_empty";
        public static final String SIZE_VALID = "DV_MULTIMEDIA.Size_valid";
    }

    public static final class DV_ORDERED {

        private DV_ORDERED() {
        }

        public static final String NORMAL_RANGE_AND_STATUS_CONSISTENCY = "DV_ORDERED.Normal_range_and_status_consistency";
        public static final String NORMAL_STATUS_VALIDITY = "DV_ORDERED.Normal_status_validity";
    }

    public static final class DV_PARSABLE {

        private DV_PARSABLE() {
        }

        public static final String FORMALISM_VALID = "DV_PARSABLE.Formalism_valid";
    }

    public static final class DV_PERIODIC_TIME_SPECIFICATION {

        private DV_PERIODIC_TIME_SPECIFICATION() {
        }

        public static final String VALUE_VALID = "DV_PERIODIC_TIME_SPECIFICATION.Value_valid";
    }

    public static final class DV_PROPORTION {

        private DV_PROPORTION() {
        }

        public static final String FRACTION_VALIDITY = "DV_PROPORTION.Fraction_validity";
        public static final String PERCENT_VALIDITY = "DV_PROPORTION.Percent_validity";
        public static final String PRECISION_VALIDITY = "DV_PROPORTION.Precision_validity";
        public static final String TYPE_VALIDITY = "DV_PROPORTION.Type_validity";
        public static final String UNITARY_VALIDITY = "DV_PROPORTION.Unitary_validity";
        public static final String VALID_DENOMINATOR = "DV_PROPORTION.Valid_denominator";
    }

    public static final class DV_QUANTIFIED {

        private DV_QUANTIFIED() {
        }

        public static final String MAGNITUDE_STATUS_VALID = "DV_QUANTIFIED.Magnitude_status_valid";
    }

    public static final class DV_TEXT {

        private DV_TEXT() {
        }

        public static final String ENCODING_VALID = "DV_TEXT.Encoding_valid";
        public static final String FORMATTING_VALID = "DV_TEXT.Formatting_valid";
        public static final String LANGUAGE_VALID = "DV_TEXT.Language_valid";
    }

    public static final class DV_URI {

        private DV_URI() {
        }

        public static final String VALUE_VALID = "DV_URI.Value_valid";
    }

    public static final class EHR {

        private EHR() {
        }

        public static final String COMPOSITIONS_VALID = "EHR.Compositions_valid";
        public static final String CONTRIBUTIONS_VALID = "EHR.Contributions valid";
        public static final String DIRECTORY_IN_FOLDERS = "EHR.Directory_in_folders";
        public static final String DIRECTORY_VALID = "EHR.Directory_valid";
        public static final String EHR_ACCESS_VALID = "EHR.Ehr_access_valid";
        public static final String EHR_STATUS_VALID = "EHR.Ehr_status_valid";
        public static final String FOLDERSS_VALID = "EHR.Folderss_valid";
    }

    public static final class ELEMENT {

        private ELEMENT() {
        }

        public static final String INV_NULL_FLAVOUR_INDICATED = "ELEMENT.Inv_null_flavour_indicated";
        public static final String INV_NULL_FLAVOUR_VALID = "ELEMENT.Inv_null_flavour_valid";
        public static final String INV_NULL_REASON_VALID = "ELEMENT.Inv_null_reason_valid";
    }

    public static final class ENTRY {

        private ENTRY() {
        }

        public static final String ENCODING_VALID = "ENTRY.Encoding_valid";
        public static final String IS_ARCHETYPE_ROOT = "ENTRY.Is_archetypeRoot";
        public static final String LANGUAGE_VALID = "ENTRY.Language_valid";
    }

    public static final class EVENT_CONTEXT {

        private EVENT_CONTEXT() {
        }

        public static final String LOCATION_VALIDITY = "EVENT_CONTEXT.Location_validity";
        public static final String SETTING_VALID = "EVENT_CONTEXT.Setting_valid";
    }

    public static final class FEEDER_AUDIT_DETAILS {

        private FEEDER_AUDIT_DETAILS() {
        }

        public static final String SYSTEM_ID_VALID = "FEEDER_AUDIT_DETAILS.System_id_valid";
    }

    public static final class HISTORY {

        private HISTORY() {
        }

        public static final String EVENTS_VALID = "HISTORY.Events_valid";
    }

    public static final class INSTRUCTION_DETAILS {

        private INSTRUCTION_DETAILS() {
        }

        public static final String ACTIVITY_PATH_VALID = "INSTRUCTION_DETAILS.Activity_path_valid";
    }

    public static final class INTERVAL {

        private INTERVAL() {
        }

        public static final String LIMITS_CONSISTENT = "INTERVAL.Limits_consistent";
        public static final String LOWER_INCLUDED_VALID = "INTERVAL.Lower_included_valid";
        public static final String UPPER_INCLUDED_VALID = "INTERVAL.Upper_included_valid";
    }

    public static final class INTERVAL_EVENT {

        private INTERVAL_EVENT() {
        }

        public static final String MATH_FUNCTION_VALIDITY = "INTERVAL_EVENT.Math_function_validity";
    }

    public static final class ISM_TRANSITION {

        private ISM_TRANSITION() {
        }

        public static final String CURRENT_STATE_VALID = "ISM_TRANSITION.Current_state_valid";
        public static final String TRANSITION_VALID = "ISM_TRANSITION.Transition_valid";
    }

    public static final class ITEM_TABLE {

        private ITEM_TABLE() {
        }

        public static final String VALID_NUMBER_OF_ROWS = "ITEM_TABLE.Valid_number_of_rows";
        public static final String VALID_STRUCTURE = "ITEM_TABLE.Valid_structure";
    }

    public static final class LOCATABLE {

        private LOCATABLE() {
        }

        public static final String ARCHETYPE_NODE_ID_VALID = "LOCATABLE.Archetype_node_id_valid";
    }

    public static final class OBJECT_REF {

        private OBJECT_REF() {
        }

        public static final String NAMESPACE_VALID = "OBJECT_REF.Namespace_valid";
    }

    public static final class PARTICIPATION {

        private PARTICIPATION() {
        }

        public static final String FUNCTION_VALID = "PARTICIPATION.Function_valid";
        public static final String MODE_VALID = "PARTICIPATION.Mode_valid";
    }

    public static final class PARTY_IDENTIFIED {

        private PARTY_IDENTIFIED() {
        }

        public static final String BASIC_VALIDITY = "PARTY_IDENTIFIED.Basic_validity";
        public static final String NAME_VALID = "PARTY_IDENTIFIED.Name_valid";
    }

    public static final class PARTY_REF {

        private PARTY_REF() {
        }

        public static final String TYPE_VALIDITY = "PARTY_REF.Type_validity";
    }

    public static final class PARTY_RELATED {

        private PARTY_RELATED() {
        }

        public static final String RELATIONSHIP_VALID = "PARTY_RELATED.Relationship_valid";
    }

    public static final class REFERENCE_RANGE {

        private REFERENCE_RANGE() {
        }

        public static final String RANGE_IS_SIMPLE = "REFERENCE_RANGE.Range_is_simple";
    }

    public static final class TERM_MAPPING {

        private TERM_MAPPING() {
        }

        public static final String MATCH_VALID = "TERM_MAPPING.Match_valid";
        public static final String PURPOSE_VALID = "TERM_MAPPING.Purpose_valid";
    }

    public static final class UID {

        private UID() {
        }

        public static final String VALUE_VALID = "UID.Value_valid";
    }

    public static final class VERSION {

        private VERSION() {
        }

        public static final String LIFECYCLE_STATE_VALID = "VERSION.Lifecycle_state_valid";
    }

    public static final class VERSION_TREE_ID {

        private VERSION_TREE_ID() {
        }

        public static final String VALUE_FORMAT_VALID = "VERSION_TREE_ID.Value_format_valid";
        public static final String VALUE_VALID = "VERSION_TREE_ID.Value_valid";
    }
}
