version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.owasp:dependency-check-gradle
    versions:
    - 6.1.0
    - 6.1.3
    - 6.1.4
    - 6.1.5
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-jsr310
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.sun.xml.bind:jaxb-impl
    versions:
    - 3.0.0
  - dependency-name: com.sun.xml.bind:jaxb-core
    versions:
    - 3.0.0
  - dependency-name: org.antlr:antlr4
    versions:
    - 4.9.2
  - dependency-name: io.codearte.gradle.nexus:gradle-nexus-staging-plugin
    versions:
    - 0.22.0
    - 0.30.0
  - dependency-name: org.antlr:antlr4-runtime
    versions:
    - 4.9.2
