description = "tools to access OpenEHR reference model metadata"

dependencies {
    api project(':aom')
    api project(':bmm')

    testImplementation project(':archie-utils')
    testImplementation project(':base')
    testImplementation project(':openehr-rm')
    testImplementation project(':test-rm')

    testImplementation(libs.guava)
}
