description = "Basic utilities for use in the archie library"

dependencies {
    api(libs.jackson.databind)
    api(libs.jackson3.databind)

    implementation project(':base')
    implementation project(':grammars')

    implementation(libs.guava)
    implementation(libs.kryo)
    implementation(libs.threeten.extra)
}
